### ISSUE TITLE
gensfenが途中で落ちる

### ISSUE THREAD

**Issue by tn870** [yaneurao/YaneuraOu#101]
gensfenコマンドを実行し、数万局面生成した段階で落ちます。(スレッド数を変えても同様)
VS2019でデバック実行したところ、affine_transform.h 105行目でアクセス違反が発生しました。
また、このときproduct m256i_i8 と m256i_u8の要素に全角文字が含まれおり、文字列中に無効な文字があると警告が出ています。

実行環境
OS : Windows 10 1903
CPU : Ryzen7 3700X
RAM : 32 GB

**Comment by yaneurao** [comment]
いま出先で確認できないのですが、その命令、指定アドレスの内容を8bit整数×32個とみなして内積とるような命令だと思うので、指定先に何が格納されていてもそれが理由では落ちないと思います。単なるアクセス違反なのでは。

現象の再現できる評価関数ファイルと再現手順をメールもらえれば、調査します。
