### ISSUE TITLE
BookOnTheFlyで正しく定跡を検索できないことがある

### ISSUE THREAD

**Issue by avksus** [yaneurao/YaneuraOu#102]
BookOnTheFly有効の場合にソート済みの定跡を使っても一部の局面がヒットしないことがあります。
例えば、以下のような小さな定跡ファイルを作ってBookOnTheFly有効で平手初期局面を読むと存在するはずなのにヒットしません。
BookOnTheFlyの実装に何らかの問題があるのではないでしょうか。

--------------------------------------------------------
#YANEURAOU-DB2016 1.00
sfen lnsgkgsnl/1r5b1/ppppppppp/9/9/7P1/PPPPPPP1P/1B5R1/LNSGKGSNL w - 2
3c3d 7g7f -59 32 1
8c8d 2f2e -64 20 1
4a3b 2f2e -64 20 1
6a5b 2f2e -95 0 1
7a6b 2f2e -97 8 1
3a4b 2f2e -100 0 1
7a7b 2f2e -119 0 1
1c1d 2f2e -124 0 1
9c9d 2f2e -124 0 1
sfen lnsgkgsnl/1r5b1/ppppppppp/9/9/8P/PPPPPPPP1/1B5R1/LNSGKGSNL w - 2
3c3d 6i7h -14 1 1
sfen lnsgkgsnl/1r5b1/ppppppppp/9/9/9/PPPPPPPPP/1B5R1/LNSGKGSNL b - 1
2g2f 3c3d 59 33 1
sfen lnsgkgsnl/1r5b1/ppppppppp/9/9/9/PPPPPPPPP/1BG4R1/LNS1KGSNL w - 2
8c8d 7g7f -53 21 1
--------------------------------------------------------

また、この件とは無関係で些細なものなのですが、ファイルに空行が入っている場合（テラショック定跡700だとファイル末尾に空行がある）のBookOnTheFlyの挙動もおかしい気がします。
その局面を出すと定跡にヒットして定跡の指し手を候補手として出力しているのに、別に通常の探索を開始してしまいます。

あと、公開されているテラショック定跡700はソート済みのはずですが、やねうら王4.88でテラショック定跡700に対してsortのコマンドを打つとファイルサイズが変わるのですが、これって重複局面があるからでしょうか？？

**Comment by avksus** [comment]
なお、ここで書いた小さな定跡ファイルはテラショック定跡から抜き出したものです。
実際には色々な定跡ファイル（ソート済み）でBookOnTheFly有効時にヒットしない局面があるのですが、あくまで簡単に再現できる例として挙げました。

**Comment by yaneurao** [comment]
ご報告ありがとうございます。

BookOnTheFlyは、テキストファイルを無理やりテキストとみなして二分探索しているので、そのときの行バッファの関係で定跡ファイルが小さいと誤作動する何かはあるような気がしてます。

10月入ったらまた開発に戻ってくるのでそのときにじっくりソースコードを確認します。(｀･ω･´)ｂ

**Comment by avksus** [comment]
ご返信ありがとうございました！

**Comment by yaneurao** [comment]
遅くなって申し訳ありません。確かに定跡にhitしないケースがありました。二分探索の最後の処理を私が勘違いしていました。大変失礼しました。以下のcommitで修正してありますので、ご確認いただければと思います。

https://github.com/yaneurao/YaneuraOu/commit/c75c98b214cf514202dd90ec9c6fddbc375daf4a
