### ISSUE TITLE
nodestimeを設定すると2手目から即指しになる

### ISSUE THREAD

**Issue by gewsd** [yaneurao/YaneuraOu#104]
nodestimeを使おうとすると1手目はちゃんと指定した時間考えてくれますが2手目からノータイムで指すようになってしまいます。
その手を指すために思考したノード数ではなく通算のノード数をカウントしてしまっているのでは？

**Comment by yaneurao** [comment]
これ原因を調べたところ、秒読みを考慮していなかったのが原因なのですけども、それとは別に、将棋(やねうら王)の場合、NetworkDelay,NetworkDelay2やMinimumThinkingTimeなどの影響も計算しないといけなくて、そのへんまできちんと計算しようと思うと時間制御のコードがすごく複雑化するというのと、そもそもこの機能要らないんじゃ…みたいに思えてきたのでこの機能は削除することにします。ご期待の添えず申し訳ありません。
