### ISSUE TITLE
SkillLevelのオプション名について

### ISSUE THREAD

**Issue by cfewl** [yaneurao/YaneuraOu#111]
すみません質問なのですが・・・

Android版をビルドして動作確認したのですがよく使われているShogiDroidというアプリだと一部の設定が正常に動かないことが分かりました。
調べてみるとShogiDroidの作者の方はOwnBookを追加してSkillLevelをUSI_SKillLevelに変更してビルドしているということが分かりました。
やねうら王の側のオプション名を変更するのはまずいのでしょうか？

http://siganus.php.xdomain.jp/phpBB3/viewtopic.php?t=347
> 
> 投稿記事by 管理人 » 2019年1月03日(木) 15:54
> 
> オプションのネーミングは一応USIは規約があって、定跡のON/OFFはUSI_OwnBookという名前になってます。
> ShogiDroidではこれに元になったチェスのOwnBookにも対応してます。
> 
> SkillLevelはUSI側にないので（USI_Strengthという似たようなものはある）、
> StockfishのSKill LevelとそれをUSI風のUSI_SKillLevelに対応しています。
> 
> 基本的にGUI側に共通設定を持っておくオプションは規約にそったほうがよいかと、
> なのでこれらはGUI側ではなく、エンジン側でオプション名を合わせたほうがよいと思います。

**Comment by yaneurao** [comment]
USI_SKillLevelに関してはUSI原案で予約されてるだけではないですかね。そのUSI原案もいまやサイト自体が見れないので、まあ、厳密に従わなくてもいいかという感じで捉えてます。😅

http://yaneuraou.yaneu.com/2016/01/10/usi%E3%83%97%E3%83%AD%E3%83%88%E3%82%B3%E3%83%AB%E3%81%AE%E8%A9%B0%E5%B0%86%E6%A3%8B%E3%81%BE%E3%82%8F%E3%82%8A/

オプション名とその意味はなるべくStockfishに近くしておきたかったので、"SkillLevel"としたんですけど、ShogiDroidが"USI_SkillLevel"と"USI_OwnBook"に対応しているのであれば、これらのオプションに準拠させますかね…。(前者は"SkillLevel"→"USI_SkillLevel"にリネーム、後者は"USI_OwnBook"というオプションの追加)

**Comment by yaneurao** [comment]
http://yaneuraou.yaneu.com/2020/03/09/%e3%82%84%e3%81%ad%e3%81%86%e3%82%89%e7%8e%8b%e3%81%ae%e3%82%a8%e3%83%b3%e3%82%b8%e3%83%b3%e3%82%aa%e3%83%97%e3%82%b7%e3%83%a7%e3%83%b3%e3%82%92usi%e3%83%97%e3%83%ad%e3%83%88%e3%82%b3%e3%83%ab/

**Comment by yaneurao** [comment]
ソースコードに反映しました。
https://github.com/yaneurao/YaneuraOu/commit/a9db04692302b5cda91c288b310434d6fa29b19c

何か問題があれば教えてください。😅

**Comment by cfewl** [comment]
疑問が解消しました
ありがとうございました！
