### ISSUE TITLE
駒の価値が最適化されていない

### ISSUE THREAD

**Issue by krmttknr** [yaneurao/YaneuraOu#112]
KOMA型のやねうら王を見ていて思ったのですが、駒の価値は本当にこれでいいのでしょうか。
元々は、駒の価値がおかしくても(SEEなどを除けば)KKPによって学習した値が加算されるので気にする必要がないということで、Aperyの平岡さんが雰囲気で決めた値だったはず。

他のソフトを調べてみると、技巧ではparams.binに学習した駒の価値が入っています。

> #include "evaluation.h"
> int main(void) {
>   std::unique_ptr<EvalParameters> g_eval_params(new EvalParameters);
>   std::FILE* fp = std::fopen("params.bin", "rb");
>   std::fread(g_eval_params.get(), sizeof(EvalParameters), 1, fp);
>   std::fclose(fp);
>   for (PieceType pt : Piece::all_piece_types())
>     std::printf("%s %d\n", Piece(kBlack, pt).ToSfen().c_str(), g_eval_params->material[pt]);
> }

として技巧2のparams.binから取り出した値とやねうら王(Apery)の値を大雑把にスケールを合わせて比較してみます。

> 駒　技巧　やねうら王
> 歩兵　99　83
> 香車　265　289
> 桂馬　286　372
> 銀将　441　455
> 金将　521　496
> 角行　668　786
> 飛車　729　910
> と金　615　496
> 成香　540　496
> 成桂　569　496
> 成銀　573　496
> 龍馬　957　868
> 龍王　1096　1282

こうしてみると、やねうら王は歩や金を過小評価し、大駒を過大評価していることが分かります。
実際の例でいうと例えば飛と金桂の2枚替えをしたときなどに逆転現象が起きています。

KPPTなどの既存の評価関数はこれまでの駒の価値を前提に学習しているので変更するとまずいようにも思いますが、KOMA型は技巧の値にしたほうが強くなるのではないでしょうか。
人間が見た場合に分かりやすい100刻みの数値とした場合でも、金を上げて大駒を下げて歩100　香300　桂400　銀500　金600　角800　飛900　と600　杏600　圭600　全600　馬1100　龍1200くらいにしたほうが適切な値に近くなります。

**Comment by yaneurao** [comment]
以前、実験した限りは、駒点を調整してもR50以内の差しかなかったので、まあ、そのへんは適当でいいかなと…。(ほとんどの局面において調整した影響が出ないので..)

**Comment by krmttknr** [comment]
R50って小さいですかね？
デメリットとしては、技巧の数値をパクるのは出村さんに悪いし新たに調整するのは面倒くさいって感じでしょうか。
それとも他にも理由があって、こちらで調整してプルリク送ったりするのもやめたほうがいい状況ですか？

**Comment by yaneurao** [comment]
うおー。出先だったもので、あとで返信しようと思って、返信忘れてました。シュミマセン…。

> それとも他にも理由があって、こちらで調整してプルリク送ったりするのもやめたほうがいい状況ですか？

数値を調整したプルリクは歓迎です。(｀･ω･´)ｂ
私の予想ではそんなに変わらないと思うんですけど…。

**Comment by yaneurao** [comment]
とりま、いったんcloseします。チューニング等のプルリクは歓迎です。
