### ISSUE TITLE
makebookでnoneが出力されることがある

### ISSUE THREAD

**Issue by bleu48** [yaneurao/YaneuraOu#113]
最新のバイナリlearn_avx2＋Kristallweizen評価関数でのことです。
いくつかの局面で定跡を掘った際に「none none 0 0 1」などの行が出ることがあります。
multipv 3の4行目に出たりするので余計なものと思います。

局面依存があるかどうか分かりませんが例えば以下の局面depth28で出ました。
sfen sn1gk3l/4s4/p2pp1+P1p/1p3+b1r1/9/2P+BLp3/PG1PP3P/3K1PS2/LNS1GG1NL w Prn4p 74

**Comment by yaneurao** [comment]
定跡として書き出されるの意味ですか？それともPVの表示として出力されるという意味ですか？その前後を含めたログをここに貼り付けていただけませんでしょうか。

**Comment by bleu48** [comment]
定跡出力ですが少し早とちりでした。
色々試行した結果mergeで混入します。
混入パターンはmerge前の定跡の最終行でした。
read_book内で最終の空行をnoneと誤解しているようです。
対戦時は意味ありませんがmergeした際に定跡ファイルに具現化してしまいます。
clusterオプションで並列生成してたもので多量に混入しました。

**Comment by yaneurao** [comment]
うおー、なるほど。詳細レポート、ありがとうございます。のちほど修正いたします。

**Comment by yaneurao** [comment]
お待たせしました！修正しました。(マージの動作をテストしてませんが、read_book()で空行を読み込まないことは確認しました。) 何かあればまた教えてください。

https://github.com/yaneurao/YaneuraOu/commit/1048b6a1874ead3e385e5c62064cf790a9bdebea
