### ISSUE TITLE
カンマの右側が先に評価される可能性

### ISSUE THREAD

**Issue by windfall-shogi** [yaneurao/YaneuraOu#114]
# バグと思われる内容
カンマ演算子の左右の評価順序は環境依存のはず。
そのため、pop_backが先に評価されて、メモリリークが発生する。

# 問題の場所
[https://github.com/yaneurao/YaneuraOu/blob/master/source/thread.cpp#L97](https://github.com/yaneurao/YaneuraOu/blob/master/source/thread.cpp#L97)

```
void ThreadPool::set(size_t requested)
{
	if (size() > 0) { // いったんすべてのスレッドを解体(NUMA対策)
		main()->wait_for_search_finished();

		while (size() > 0)
			delete back(), pop_back();   <-これ
	}
```

# 解決方法
カンマ演算子で連結せずに独立した文にする。

**Comment by windfall-shogi** [comment]
カンマ演算子の評価は左側から行われることが保証されるので、この指摘は当たらない。
[Built-in comma operator](https://en.cppreference.com/w/cpp/language/operator_other#Built-in_comma_operator)
（カンマ演算子のオーバロードもされていないはずなので、c++17以前においてもやはり当たらない。）

**Comment by yaneurao** [comment]
(ﾟдﾟ)??

始まったと思ったら、closeしてますた。(^^ゞ
問題ないようで、何よりです。
