### ISSUE TITLE
The purpose of re-search in gensfen on search_depth <= 0

### ISSUE THREAD

**Issue by Sopel97** [yaneurao/YaneuraOu#121]
I was looking at the learning code ported to stockfish, and I was wondering what the purpose of https://github.com/yaneurao/YaneuraOu/blob/master/source/learn/learner.cpp#L644-L648 is and whether it could be replaced by simply clamping search_depth to always be positive?

**Comment by yaneurao** [comment]
We wanted to set the search depth to 0 (for qsearches only) or negative (for special qsearches only) for our experiments, so the code assumes that the depth is non-positive.

But it's not a code that makes much sense nowadays.
