### ISSUE TITLE
CI入れるなら

### ISSUE THREAD

**Issue by wakatsuki-moe** [yaneurao/YaneuraOu#125]
私だけですかもですが

CI(Action)がリポジトリに入っての時にうまくいかなく

具体的には、本リポジトリからプルして自前のにプッシュ時にエラーでて；
自前にはプッシュできてないと思ってリベースもしてしまって
結果はプッシュはできていて自前でのリベース等は;^^

ごめんなさい
issuesへ書く内容では無いですね

自前は消して再Folkでし直しました

告知あたらと思います

**Comment by yaneurao** [comment]
言葉の意味はわかりませんが、CI buildの修正しました。https://github.com/yaneurao/YaneuraOu/commit/0cff24416e7d4c51d6460bfa299cf6193eb20d61
