### ISSUE TITLE
v5.20 -> v5.30 bad evaluation?

### ISSUE THREAD

**Issue by Tellmarch** [yaneurao/YaneuraOu#139]
On the most recent version (5.33), and since v5.30 or v5.21, there seem to be a problem when evaluating some positions with a time limit.

Position: sfen l6nl/6k2/+P3p2p1/1B1p1Pp1p/1p7/7nP/3P1SP1L/2+p3GK1/L6+r1 b B2G2S5Prgs2np 0

Expected evaluation: **mate -8**

v4.91-v5.20 evaluation (byoyomi 20000): **mate -8**
v.5.30-v5.33 evaluation (byoyomi 20000): **cp 1953** (info depth 2 seldepth 3 score cp 1953 nodes 616 nps 205333 time 3)
v.5.30-v5.33 evaluation (go infinite): **mate -8** (info depth 17 seldepth 9 score mate -8 nodes 26057 nps 2368818 time 11)

This is problematic for game analysis, as it shows a very high score (winning) when it should be very low (losing).

Example session:
Built with "make tournament", eval function elmo_wcsc29
Reproduced on two different computers

**Bad session (v5.30)**
```
usi
id name YaneuraOu NNUE 5.30 64AVX2BMI2 TOURNAMENT
(...)
usiok
isready
info string Hash table allocation: Linux Large Pages used.
info string eHash Clear begin , Hash size =  1024[MB]
info string USI_Hash Clear begin , Hash size =  16[MB]
(...)
readyok
position sfen l6nl/6k2/+P3p2p1/1B1p1Pp1p/1p7/7nP/3P1SP1L/2+p3GK1/L6+r1 b B2G2S5Prgs2np 0
go btime 0 wtime 0 byoyomi 20000
info depth 1 seldepth 1 score cp 345 nodes 178 nps 89000 time 2 pv 2h2i
info depth 2 seldepth 3 score cp 1953 nodes 616 nps 205333 time 3 pv 2h2i 2f3h+ 4g3h
bestmove 2h2i ponder R*1i
```

**Good session (v5.20)**
```
usi
id name YaneuraOu NNUE 5.20 64AVX2BMI2 TOURNAMENT
(...)
usiok
isready
info string Hash table allocation: Linux Large Pages used.
info string eHash Clear begin , Hash size =  1024[MB]
info string Hash Clear begin , Hash size =  16[MB]
(...)
readyok
position sfen l6nl/6k2/+P3p2p1/1B1p1Pp1p/1p7/7nP/3P1SP1L/2+p3GK1/L6+r1 b B2G2S5Prgs2np 0
go btime 0 wtime 0 byoyomi 20000
info depth 1 seldepth 1 score cp 345 nodes 176 nps 88000 time 2 pv 2h2i
info depth 2 seldepth 3 score cp 1953 nodes 395 nps 197500 time 2 pv 2h2i 2f3h+ 4g3h
info depth 16 seldepth 9 score mate -8 nodes 23394 nps 2126727 time 11 pv 2h2i R*1i 2i2h S*3i 2h2g 1i1h+ 2g2f G*3e
bestmove 2h2i ponder R*1i
```

**Comment by Tellmarch** [comment]
The impact of this issue is bad evaluation graphs.

Here is the comparison for the same game, same computer, same settings, but version 4.91 vs version 5.33. The latest version shows jumps in evaluation when the game is in the tsume sequence.

![Screenshot from 2020-11-28 22-20-11](https://user-images.githubusercontent.com/13988079/100526454-66ee1a80-31c9-11eb-87ef-29b56db4a081.png)
![Screenshot from 2020-11-28 22-30-38](https://user-images.githubusercontent.com/13988079/100526455-68b7de00-31c9-11eb-9924-63bf759a53f9.png)

**Comment by ddugovic** [comment]
Hm, I wonder... shouldn't `info ...` always print right before `bestmove`?

Perhaps there is a bug in general with `go btime 0 wtime 0 byoyomi 20000` since I would expect to see `info ... time 20000` or similar right before `bestmove`.

**Comment by yaneurao** [comment]
YaneuraOu can't see the mate of those 8 plies in the short time. Try using the latest version of YaneuraOu (V5.40) in combination with the latest NNUE evaluation function (such as Suisho).

**Comment by Tellmarch** [comment]
Sorry, but that's wrong. YaneuraOu can definitely see the mate in the 20 seconds specified, it takes only a few milliseconds with "go infinite".
The bug is that it displays the wrong evaluation/info, jumping dramatically as shown on the screenshot (advantage Sente 2000 instead of Gote winning by mate).
The info specified "info depth 2 seldepth 3 score cp 1953 nodes 616 nps 205333 time 3 pv 2h2i 2f3h+ 4g3h"  shows only a depth of 2, when asked to compute for 20000 milliseconds...

**Comment by Tellmarch** [comment]
The bug is still present as of last commit (Today Dec 30th):

Note that if running the same "go btime" command a second time, then the output is correct, suggesting that it was already computed in the first evaluation, but not displayed properly.

```
usi
id name YaneuraOu NNUE 5.40 64AVX2 TOURNAMENT
id author by yaneurao
option name Threads type spin default 4 min 1 max 512
option name USI_Hash type spin default 16 min 1 max 33554432
option name USI_Ponder type check default false
option name MultiPV type spin default 1 min 1 max 800
option name NetworkDelay type spin default 120 min 0 max 10000
option name NetworkDelay2 type spin default 1120 min 0 max 10000
option name MinimumThinkingTime type spin default 2000 min 1000 max 100000
option name SlowMover type spin default 100 min 1 max 1000
option name MaxMovesToDraw type spin default 0 min 0 max 100000
option name DepthLimit type spin default 0 min 0 max 2147483647
option name NodesLimit type spin default 0 min 0 max 9223372036854775807
option name EvalDir type string default eval
option name WriteDebugLog type check default false
option name EnteringKingRule type combo default CSARule27 var NoEnteringKing var CSARule24 var CSARule27 var TryRule
option name GenerateAllLegalMoves type check default false
option name USI_OwnBook type check default true
option name NarrowBook type check default false
option name BookMoves type spin default 16 min 0 max 10000
option name BookIgnoreRate type spin default 0 min 0 max 100
option name BookFile type combo default standard_book.db var no_book var standard_book.db var yaneura_book1.db var yaneura_book2.db var yaneura_book3.db var yaneura_book4.db var user_book1.db var user_book2.db var user_book3.db var book.bin
option name BookDir type string default book
option name BookEvalDiff type spin default 30 min 0 max 99999
option name BookEvalBlackLimit type spin default 0 min -99999 max 99999
option name BookEvalWhiteLimit type spin default -140 min -99999 max 99999
option name BookDepthLimit type spin default 16 min 0 max 99999
option name BookOnTheFly type check default false
option name ConsiderBookMoveCount type check default false
option name BookPvMoves type spin default 8 min 1 max 246
option name IgnoreBookPly type check default false
option name SkillLevel type spin default 20 min 0 max 20
option name Contempt type spin default 2 min -30000 max 30000
option name ContemptFromBlack type check default false
option name PvInterval type spin default 300 min 0 max 100000
option name ResignValue type spin default 99999 min 0 max 99999
option name ConsiderationMode type check default false
option name OutputFailLHPV type check default true
usiok
isready
info string Hash table allocation: Linux Large Pages used.
info string EvalDirectory = /home/jean/shogi/engines/newy2/YaneuraOu/source/eval
info string loading eval file : eval/nn.bin
info string read book file : book/standard_book.db
info string Error! : can't read file : book/standard_book.db
info string USI_Hash Clear begin , Hash size =  16[MB]
info string USI_Hash Clear done.
readyok
position sfen l6nl/6k2/+P3p2p1/1B1p1Pp1p/1p7/7nP/3P1SP1L/2+p3GK1/L6+r1 b B2G2S5Prgs2np 0
go btime 0 wtime 0 byoyomi 20000
info depth 1 seldepth 1 score cp 345 nodes 148 nps 74000 time 2 pv 2h2i
info depth 2 seldepth 3 score cp 1953 nodes 384 nps 192000 time 2 pv 2h2i 2f3h+ 4g3h
bestmove 2h2i ponder R*1i
go btime 0 wtime 0 byoyomi 20000
info depth 1 seldepth 1 score mate -8 nodes 9 nps 4500 time 2 pv 2h2i
info depth 2 seldepth 2 score mate -8 nodes 64 nps 32000 time 2 pv 2h2i R*1i 2i2h
bestmove 2h2i ponder R*1i
```

**Comment by yaneurao** [comment]
Thank you for the report. I'll look into it later.

**Comment by yaneurao** [comment]
I'm sorry to keep you waiting. I have fixed this issue.

Initially, I thought the issue was that the evaluation output by the search unit was wrong, but in fact, the problem was that the search unit did not output the final PV at the end of the countdown.

https://github.com/yaneurao/YaneuraOu/commit/df8283418acfe0647c8464cb98fe104652ae4657

**Comment by Tellmarch** [comment]
Thank you for the fix! I really appreciate all the work you do on YaneuraOu.
