### ISSUE TITLE
ソースコードの整形ルール

### ISSUE THREAD

**Issue by mizar** [yaneurao/YaneuraOu#140]
現在のソースコードは、インデントだけでも tab、2space、4space が混在しており、pull requestを送ったりする際に何に合わせたら良いのか分からなくなる状況です。

> そういや、やねうら王は基本4 tabです。スペースに変換されているところがいくつかあるかもですが、基本4 tabで、NNUEとかプルリクもらったままマージしたので2 tabになっている箇所がありますが、何か手を入れたときに 4 tab化してます。
> // 2 tabのままになっているのは私がまだ未踏の地だということですね。

という話ですが、そういう所を手伝うにしても、ソースコードの整形部分ばかりでdiffが膨れ上がってしまうので支障が大きそうです。

clang-format などの整形ツールで使えるようなルールの作成を進められないものでしょうか。

## 参考:

- [Google C++ スタイルガイド 日本語全訳](https://ttsuki.github.io/styleguide/cppguide.ja.html)
- [ClangFormatスタイルオプション](http://algo13.net/clang/clang-format-style-oputions.html)
- `source/eval/nnue/` 以下に clang-format を適用した例:
  - Google C++ スタイルガイドに近い形 ( + Includeのソート無し、1行の文字数制限無し)
    [`clang-format -style="{BasedOnStyle: Google, SortIncludes: false, ColumnLimit: 0}"`](https://github.com/mizar/YaneuraOu/commit/64403ab38a068ad33c91feb024728422f93edf58)
  - インデント幅4
    [`clang-format -style="{BasedOnStyle: Google, SortIncludes: false, ColumnLimit: 0, IndentWidth: 4}"
`](https://github.com/mizar/YaneuraOu/commit/37aa6696f09f3ef8dda1e55a7b68ea75c4e58a82)
  - インデント幅4, タブ幅4, インデントにタブ使用
    [`clang-format -style="{BasedOnStyle: Google, SortIncludes: false, ColumnLimit: 0, IndentWidth: 4, TabWidth: 4, UseTab: ForIndentation }"`](https://github.com/mizar/YaneuraOu/commit/e204bb8ff5d9c1cca462398242c229bf2589b5eb)
  - インデント幅4, タブ幅4, インデントと継続行の字下げにタブ使用
    [`clang-format -style="{BasedOnStyle: Google, SortIncludes: false, ColumnLimit: 0, IndentWidth: 4, TabWidth: 4, UseTab: ForContinuationAndIndentation }"`](https://github.com/mizar/YaneuraOu/commit/921228c273be284f8cfe7d8ac08d32cfcd44eaf8)

**Comment by mizar** [comment]
```
clang-format -style="{BasedOnStyle: Google, SortIncludes: false, ColumnLimit: 0, IndentWidth: 4}" -dump-config > .clang-format
```
例えばこのような形で整形ルールを書き出し、出力した `.clang-format` ファイル をプロジェクトのルート、もしくは source/ 等に置き、

例: PowerShell のターミナル上にて
```
clang-format -style=file -i $(Get-ChildItem *h,*.cpp -Recurse|% FullName)
```

のようなコマンドを何らかの形で実行する事で整形済みのソースコードを得る、といった方向性を将来的に取れれば、とも思っています。

**Comment by mizar** [comment]
bitboard tableの定義など、整形済みで崩したくないコード部分については、

```
// clang-format off
```

（崩したくないソースコードブロック）

```
// clang-format on
```

のようなコメント行で囲う事で、clang-formatによる自動整形を抑止する部分を作れるようです。

**Comment by yaneurao** [comment]
私の開発環境はVisual Studioなので、Visual Studioのデフォルト(4 tab)を想定してます。
プルリクは、tab が半角spaceに変換されていても良いですが、その場合もtabに相当するものは半角space 4個であって欲しいですね。(半角space 2個になっているものは、私がいじったときにtabに変換することがあります)

**Comment by mizar** [comment]
> 私の開発環境はVisual Studioなので、Visual Studioのデフォルト(4 tab)を想定してます。

Visual Studio であれば、プロジェクトルートに .editorconfig ファイルを配置する事でコードスタイルの設定を行える可能性がありますね。
https://docs.microsoft.com/ja-jp/visualstudio/ide/create-portable-custom-editor-options?view=vs-2019

**Comment by mizar** [comment]
VS2019の場合、デフォルトで対応するバージョンは clang-format version 5.0 とやや古い （最新は 11.0.0） ですが、プロジェクト内に .clang-format や .editorconfig を配置すればそれを読んで使ってくれるようです。

https://docs.microsoft.com/ja-jp/visualstudio/ide/reference/options-text-editor-c-cpp-formatting?view=vs-2019

> ## ClangFormat オプションを構成する
> ClangFormat のサポートは、既定で有効になっています。 一般的な書式設定規則である LLVM、Google、Chromium、Mozilla、WebKit のうち、すべてのプロジェクトに適用するものを選択できます。 また、カスタム書式定義の .clang-format または _clang-format ファイルを作成できます。 そのようなファイルがプロジェクト フォルダーに置かれている場合、Visual Studio は、そのフォルダーとそのサブフォルダーのすべてのソース コード ファイルの書式設定にそのファイルを使用します。
> 既定では、Visual Studio は clangformat.exe をバックグラウンドで実行し、ユーザーが入力すると書式設定を適用します。 書式設定コマンド **Format Document (Ctrl + K、Ctrl + D)** または **Format Selection (Ctrl + K、Ctrl + F)** を手動で呼び出す場合にのみ、clangformat.exe を実行するように指定することもできます。
> ## インデント、改行、間隔、折り返しのページ
> これらのページでは、さまざまな書式設定をカスタマイズできますが、ClangFormat が有効になっている場合は無視されます。

![image](https://user-images.githubusercontent.com/68691/100557043-cba09680-32e9-11eb-936d-3a05c4b5fa63.png)

**Comment by yaneurao** [comment]
とりま、.editorconfigで4タブを強制(?)するようになっていると思うので、それでよろしいかと。
その他は、Visual Studioのデフォルト設定で問題ないです。

ただ、
> x = abc[123] + def[234]
>    + xyz[  56]  + w  [ 78];
のように、次の行との "[" , "]" の横方向の位置が揃っているだとか、論理的な構造に関しては対称性などが見える形になっていて欲しいというのはありますが(やねうら王のソースコード全体を見れば意味はわかるはず)、それは、あくまで希望ですね。

// とりま、プルリク時には、いまそのようになっているものを崩さないでもらえたらと。
