### ISSUE TITLE
makebookコマンド,

### ISSUE THREAD

**Issue by Handagot** [yaneurao/YaneuraOu#153]
think時(clusterで分配)に表示される思考局面数とmerge時に表示される思考局面数が異なる

**Comment by yaneurao** [comment]
おそらく、手数違いの同一局面があるからではないかと…。
// 手数違いの同一局面、clusterに分配するときに間引いておくべきではある。
// レアケースなのでまあいいかと思って放置してたような。

**Comment by Handagot** [comment]
了解しました
