### ISSUE TITLE
Handicap evaluation

### ISSUE THREAD

**Issue by ddugovic** [yaneurao/YaneuraOu#158]
test.sfen:
```
lnsgkgsnl/1r5b1/ppppppppp/9/9/9/PPPPPPPPP/1R5R1/LNSGKGSNL b - 1
```

```
#!/bin/bash
../script/build.sh -a AVX2 -c clang++ -e MATE_ENGINE -t normal && \
../build/linux/MATE/tanuki_MATE-linux-clang++-normal-AVX2 bench 16 1 5 test.sfen depth
```

**Comment by yaneurao** [comment]
> ../script/build.sh -a AVX2 -c clang++ -e MATE_ENGINE -t normal 

In the latest version of YaneuraOu, use either TANUKI_MATE_ENGINE or YANEURAOU_MATE_ENGINE to build the Mate Engine; specifying MATE_ENGINE is for older versions. Please try the latest version.

Furthermore, I think bench command is not supported by the Mate Engines.

**Comment by ddugovic** [comment]
Thanks for that advice.  Sorry, I got very confused trying to reproduce errors observed by other developers.  I think what they are trying is something like:

```
#!/bin/bash
../script/build.sh -a AVX2 -c clang++ -e YANEURAOU_ENGINE_NNUE -t normal && \
../build/linux/NNUE/YaneuraOu_NNUE-linux-clang++-normal-AVX512 bench 16 1 5 test.sfen depth
```

```
$ ./build.sh
...
./build.sh: line 3: 83466 Illegal instruction     (core dumped) ../build/linux/NNUE/YaneuraOu_NNUE-linux-clang++-normal-AVX512 bench 16 1 5 test.sfen depth
```

**Comment by mizar** [comment]
> `../build/linux/NNUE/YaneuraOu_NNUE-linux-clang++-normal-AVX512`

Why AVX512? Why not AVX2?

**Comment by mizar** [comment]
Make sure that the binary you build and the binary you launch are the same file. Why are you trying to launch the AVX512 version when you built the AVX2 version?

```
grep flags /proc/cpuinfo | uniq
```

In addition, check your CPU environment, because it seems that running the AVX512 version will not work without at least `avx512f` or `avx512bw`. Maybe you need to add other flags as well.

example:
```
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb stibp fsgsbase bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 xsaves flush_l1d arch_capabilities
```

**Comment by mizar** [comment]
> `lnsgkgsnl/1r5b1/ppppppppp/9/9/9/PPPPPPPPP/1R5R1/LNSGKGSNL b - 1`

Why do you need three rooks on the board?

**Comment by ddugovic** [comment]
Good question.  @WandererXII advises that for Lishogi this will not be required after all.
