### ISSUE TITLE
Tsume solved incorrectly

### ISSUE THREAD

**Issue by Little-Mage** [yaneurao/YaneuraOu#162]
tanuki_MATE-tournament-clang++-zen2.exe and YaneuraOu_MATE-tournament-clang++-zen2.exe say this tsume is 13 moves long when it is actually 3 moves long.
sfen 5pk2/7P1/4+R1+P1+b/8b/6R2/9/9/9/9 b 4g4s4n4l15p 1

**Comment by Little-Mage** [comment]
This tsume is also 3 moves but both exe say it is 7 moves.
sfen 9/5g1s1/8k/6+R2/9/6R1S/5B3/9/9 b b3g2s4n4l18p 1

**Comment by yaneurao** [comment]
This MateEngine is intended for practical use and does not deal with useless drop pieces. This is a specification.
