### ISSUE TITLE
MSYS2 build error 2021-05

### ISSUE THREAD

**Issue by takotakot** [yaneurao/YaneuraOu#173]
MSYS2 のビルドでエラーが出ていますが、msys2/MINGW-packages#8658 っぽいです。上流では修正に入ったようです。
迂回策を調査しています。

**Comment by takotakot** [comment]
@mizar もう調査済みだったようですね。失礼いたしました。

**Comment by mizar** [comment]
llvm/clang 12.0.0-4 以降のMSYS2パッケージではこの問題は解消済みと見られます。特に対処する必要は無さそうです。

https://packages.msys2.org/package/mingw-w64-x86_64-llvm
https://github.com/msys2/MINGW-packages/commit/a6055d83636633ad74f4f91a824cc2989feca2c9#diff-125e46f56c15d81bb2f9210bdcc4959baf788e9db4c0acfbff0148bf4416815d

**Comment by takotakot** [comment]
リリースもされたようですね。ジョブの再実行か、次のActionでは問題がなさそうです。
