### ISSUE TITLE
やねうら王詰将棋エンジンde

### ISSUE THREAD

**Issue by barcodehair** [yaneurao/YaneuraOu#174]
以下の詰将棋がメモリ１６GBの設定で解けません。
sfen 3+R1gknl/4+B1s2/6pp1/5p3/8p/9/9/9/9 b RSNPb3g2s2n3l13p 1

合駒なども出てこないので、このメモリ量で解けないのはさすがに変だと思います。
ちなみに、tanuki詰や脊尾詰なら一瞬で解けます。

**Comment by barcodehair** [comment]
すみません、タイトルの書きかけで投稿してしまいました。
内容はこのとおりで間違いありません。

**Comment by yaneurao** [comment]
報告ありがとうございます。いままとまった時間が取れないので今週末に調べたいと思います。

**Comment by yaneurao** [comment]
↓以下のプルリクで修正されていました。mergeしました。ご報告ありがとうございました。
https://github.com/yaneurao/YaneuraOu/pull/176
