### ISSUE TITLE
Support for modern CPU Architecture 

### ISSUE THREAD

**Issue by TheYoBots** [yaneurao/YaneuraOu#175]
Does YaneuraOu support the modern CPU architecture? These are the parameters: https://github.com/official-stockfish/Stockfish/blob/754fc8a8b5ca7466926d54465eeb1df4d4a481ac/src/Makefile#L172-L177 . If I’m right YaneuraOu doesn’t support `popcnt` Architecture.

**Comment by yaneurao** [comment]
Since popcnt() is a SSE4.2 instruction, the code assumes that popcnt is available when USE_SSE42 is defined. 

For example, this part.
https://github.com/yaneurao/YaneuraOu/blob/7917ee5f94a47bf07124a1f741425aeffaf8b445/source/extra/bitop.h#L116

**Comment by TheYoBots** [comment]
Thank you so much for explaining!
