### ISSUE TITLE
Running YaneuraOu in the browser

### ISSUE THREAD

**Issue by justremember** [yaneurao/YaneuraOu#177]
We at [Lishogi.org](https://github.com/WandererXII/lishogi/) are requesting a YaneuraOu version that is runnable in the browser. Theoretically, this would be possible with WASM and Emscripten. [Emscripten](https://emscripten.org/docs/introducing_emscripten/index.html) is a toolkit that compiles, with a few modifications, C or C++ code to WASM, and thus allows running those programs in the browser, inside a webpage. WASM is already supported by new versions of Firefox, Chrome, Safari, and Edge. Something similar has already been done with an NNUE chess engine by Hiroshi Ogawa ([Github repo](https://github.com/hi-ogawa/Stockfish)), who compiled the Stockfish NNUE to WASM. And so Lichess.org implemented it on their website and made a [blog post](https://lichess.org/blog/YDOKRxQAACgAREB3/stockfish-13-nnue-on-lichess) about it. Please do try it out in this [example game](https://lichess.org/kCfU0hkO#85) (works best with Chrome/Chromium).
![image](https://user-images.githubusercontent.com/14817065/119327044-23c2bf00-bcb5-11eb-8809-e294e06e4d63.png)

We would like to request this YaneuraOu client-side version for the purposes of our Shogi site. A very strong engine like YaneuraOu running in the browser would be highly beneficial towards Lishogi players, who will be able to use it to analyse their own games right after playing it. Currently our [browser analysis](https://lishogi.org/analysis) is running Fairy-Stockfish which is good in the endgame but does not do well in the opening and middlegame. Of course, we will also give proper credit, following the GPLv3 license.

**Comment by yaneurao** [comment]
I have plans, but I think it will be at the end of this year.
