### ISSUE TITLE
突然自陣内にて飛車を成ってしまう

### ISSUE THREAD

**Issue by tayayan** [yaneurao/YaneuraOu#184]
再現性が高いわけではないのですが、
YaneuraOu_6.03_NNUE-tournament-clang++-avx2において、
sfen l5snl/1r1gk1gb1/p1nspp1pp/2pp5/1pP3R2/6P2/PPSPPP2P/1BG1K1S2/LN3G1NL w 2P 28
や
sfen l6nl/1r1gksgb1/2ns1p1p1/p1p1p1P2/3p4p/PPR6/2SPPPNSP/1BG1KG3/LN6L w 4P 46
のような局面等で、後手番の読み筋に8三飛車成や8一飛車成といった非合法手が読み筋に入ってしまうといった不具合があるようです。不具合は後手番の読み筋でしか起こらず、かつ、飛車成に関する不具合である確率が高いようです（私自身は再現できておりませんが、7六歩、3四歩、2六歩と初期局面から3手進めただけの局面でも後手番に5二飛車成という読み筋が入ってしまう場合があるとの報告も受けております。）

**Comment by yaneurao** [comment]
https://github.com/yaneurao/YaneuraOu/pull/185 にて修正されているはず。
