### ISSUE TITLE
There are some problems with the software initialization on my computer 

### ISSUE THREAD

**Issue by a447961881** [yaneurao/YaneuraOu#187]
Hello, when I use ShogiGUI to run 6.0.3 nnue's avx2 or any other exe, initialization failure is displayed in the software window. When I change to Shogidokoro to run the software, the operation failure message displayed at the bottom is: Hash table allocation: Windows Large Pages not used. Excuse me, where did the settings go wrong? My CPU is 8750h supports avx2, and everything goes well when running stockfish 14. Thank you for your answer.

**Comment by a447961881** [comment]
I tried almost all exe with shogigui, including the old version of kkpt exe, all showed that the initialization failed, but I run other shogi ai including Apery_WCSC30 of another author on github, everything is normal, this situation really makes me feel very Confusion

**Comment by a447961881** [comment]
![image](https://user-images.githubusercontent.com/42687267/131331739-36ecd5fe-0bf3-4928-b1e7-197acc3495ed.png)

**Comment by yaneurao** [comment]
please read readme at first.

https://github.com/yaneurao/YaneuraOu/blob/master/docs/%E6%9C%80%E5%88%9D%E3%81%AB%EF%BC%9A%E3%82%84%E3%81%AD%E3%81%86%E3%82%89%E7%8E%8B%E9%81%8A%E3%81%B3%E6%96%B9%E8%AA%AC%E6%98%8E.txt
