### ISSUE TITLE
Question - Ubuntu

### ISSUE THREAD

**Issue by SriMethan** [yaneurao/YaneuraOu#192]
Hi I am using ubuntu how do I provide the path for EvalDir

**Comment by yaneurao** [comment]
The default value of the EvalDir Option is "eval". Create a folder named "eval" in the same folder where the executable file is located, and put the evaluation function file in the folder.

For details, please refer to the Japanese readme.
https://github.com/yaneurao/YaneuraOu/blob/master/docs/%E6%9C%80%E5%88%9D%E3%81%AB%EF%BC%9A%E3%82%84%E3%81%AD%E3%81%86%E3%82%89%E7 %8E%8B%E9%81%8A%E3%81%B3%E6%96%B9%E8%AA%AC%E6%98%8E.txt

**Comment by yaneurao** [comment]
If you are referring to the issue of not being able to specify an absolute path in EvalDir, it was fixed in the previous commit.
Thanks for letting me know.

https://github.com/yaneurao/YaneuraOu/commit/a6038834fc9049ad6ad9ca2b95df47b09f0bb2e6

**Comment by SriMethan** [comment]
@yaneurao Thankyou but the release executable cannot contain this commit is there any build script to build YaneuraOu?
