### ISSUE TITLE
6.50でのベンチマーク計測時のTotal Timeが異常に大きい

### ISSUE THREAD

**Issue by bleu48** [yaneurao/YaneuraOu#195]
今日適当に走らせてみた感想なんですが以前のバイナリに比べてTotal Timeが異常に大きくなります。
npsはほぼ変わりませんが，Total Timeが数倍規模で大きくなります。
また，シングルスレッドよりマルチスレッドの方が更に大きくなります。

取り急ぎ現象報告だけ。

**Comment by yaneurao** [comment]
ベンチマークを固定時間に変更しました。
https://github.com/yaneurao/YaneuraOu/commit/46c0312d5c9bddf1d8f964cb62a44acb48bbb68a
