### ISSUE TITLE
Wikiのよくある質問の誤字

### ISSUE THREAD

**Issue by iwkjosec** [yaneurao/YaneuraOu#245]
なぜかブログにコメントできないのでこっちに書きます

[よくある質問](https://github.com/yaneurao/YaneuraOu/wiki/%E3%82%88%E3%81%8F%E3%81%82%E3%82%8B%E8%B3%AA%E5%95%8F)の最初の見出しが全角スペースになっていて、認識されてないです

**Comment by yaneurao** [comment]
修正しておきました！ありがとうございます。

// ブログのほうは、特に何も設定していないのですが、アンチスパムのプラグインを入れているので、海外っぽいIPアドレスだと弾くとかあるのかも知れないです…。
