### ISSUE TITLE
A suspected memory leak has occurred.

### ISSUE THREAD

**Issue by KohakuBlueleaf** [yaneurao/YaneuraOu#252]
I use the fukauraou 7.61 with TensorRT and use the model from dlshogi.
I leave all setting default. with 32GB ram and RTX3090.
At first it consume about 3GB which is make sense, but the memory it consume will increase slowly(about 50~80MB per second).
Finally It will consume more than 16GB of memory after several minute. And no matter how many step I move the memory consumption is just increasing.

Althougth this situation doesn't affect anything at first, but it will cause a crash of system after it consume more than the memory I have.

Task Manager:
![image](https://user-images.githubusercontent.com/59680068/178661203-a350fb96-25f1-4bb3-9e3a-bd7a548186db.png)
Program Folder:
![image](https://user-images.githubusercontent.com/59680068/178661341-b52c8982-a3af-43e7-88b9-f04e8689cacf.png)

**Comment by KohakuBlueleaf** [comment]
@yaneurao Sorry I notice what I missed.
Since fukauraou and dlshogi use AlphaZero-like algo, there is a MCTS tree in it.
And this tree will grow up when searching so the memory consuming will increase.
So, yes, this is normal.

**Comment by yaneurao** [comment]
I understand.

If the memory consumption does not decrease after the next move is made, then it is a bug. (V7.60 had this bug. There might still be that kind of bug. If so, please let me know.) 

I'll close this issue.
