### ISSUE TITLE
material v9 が生成されない

### ISSUE THREAD

**Issue by topstone** [yaneurao/YaneuraOu#255]
素晴らしい成果物を公開いただきありがとうございます。

[#231] 以降、material v9 が生成されていないのではないかと思われます (v1 のみ生成されています)。ご確認下さい。

**Comment by yaneurao** [comment]
対応、遅くなってすみません。そんなにたくさんいらんやろということで、生成してないみたいですね。まあ、古いバージョンは残っていますし…。
