### ISSUE TITLE
gensfen not implemented for material evallearn

### ISSUE THREAD

**Issue by Smooshy30** [yaneurao/YaneuraOu#256]
The gensfen command should be available when building YANEURAOU_ENGINE_MATERIAL, using **make evallearn**
But it doesn't seem to be compiled into the executable.
Invoking usi prints the follwing:
`id name YaneuraOu MaterialLv1 7.63 64AVX2`
So it seems to be just making a normal build instead.

**Comment by yaneurao** [comment]
返信遅くなってすみません。
実装していません。それは意図したものです。
代わりに通常バージョンを、評価関数をゼロクリアして用いてください。
