### ISSUE TITLE
角歩の不成を含む詰みが読めない

### ISSUE THREAD

**Issue by barcodehair** [yaneurao/YaneuraOu#257]
角や歩の不成がからむと、短手数でも詰みが読めないことがあります。
GenerateAllLegalMoves はもちろんtrueにしています。

詰みが読めない局面の例
5B1n1/8k/6Rpp/9/9/9/1+p7/9/K8 b rb4g4s3n4l15p 1
7nk/9/7Gp/6+RP1/9/9/1+p7/9/K8 b Pr2b3g4s3n4l14p 1

バージョン7.0では問題ありませんでしたが、
以下のコミットから発生するようになったようです。
- CAPTURES_PRO_PLUSの指し手生成バグってる問題。 
ca89b8b6629cd8395079ccd61e3e68d78eea32a6

**Comment by yaneurao** [comment]
ご報告、ありがとうございます。原因まで特定していただいて、感謝です!!😁
次回の改修の時に修正しますね。

**Comment by yaneurao** [comment]
早くからご報告いただいていたのに修正が遅くなって申し訳ありません。この壊したcommitの意図通りに修正するの難しそうだなーと思って放置してました。結局、難しいので元のコードにrollbackすることにしました。ご報告、ありがとうございました。

https://github.com/yaneurao/YaneuraOu/commit/b40959f3b56dc88dc2848a72cfbe2467d93ce500
