### ISSUE TITLE
Learner::qsearch() および Learner::search() でnullポインタアクセスする

### ISSUE THREAD

**Issue by nodchip** [yaneurao/YaneuraOu#26]
Learner::qsearch() および Learner::search() で ss->pv = pv; でPV格納用のバッファのアドレスを格納したあと、init_for_search()内でmemset()で0クリアしています。このためYaneuraOu2017Early::qsearch()内でnullポインタアクセスを起こし、プログラムがクラッシュします。

https://github.com/yaneurao/YaneuraOu/blob/f35146aff827609e909aa32f68da6fd4f942ba3a/source/engine/2017-early-engine/2017-early-search.cpp#L3065

お手すきの際に確認・修正頂けませんでしょうか？よろしくお願いいたします。

**Comment by yaneurao** [comment]
ご指摘ありがとうございます。修正しました(｀･ω･´)ゞ

**Comment by nodchip** [comment]
素早い対応ありがとうございました。
