### ISSUE TITLE
Cannot use FukauraOu

### ISSUE THREAD

**Issue by rasc42** [yaneurao/YaneuraOu#262]
Sorry for writing in English. I'm using Windows 11.

I always get this error with FukauraOu:
![image](https://github.com/yaneurao/YaneuraOu/assets/5458405/cc3d2e65-bc20-45b7-b8aa-67b4bbfd3d58)

I have all necessary files:
![image](https://github.com/yaneurao/YaneuraOu/assets/5458405/df92bfe0-4a89-49c4-b8a6-defe6a5942c9)

And CUDA 11.6 is in the path:
![image](https://github.com/yaneurao/YaneuraOu/assets/5458405/081a691d-e88d-4f9d-9c1f-2d94fe65314d)

And have compatible GPU:
![image](https://github.com/yaneurao/YaneuraOu/assets/5458405/82d9ec14-8f99-4699-8e23-3002bf8905ba)

Any ideas?

Thanks.

**Comment by yaneurao** [comment]
Please try to run FukauraOu on CUI(Double-click on the FukauraOu executable file on Windows Explorer.), not from GUI(ShogiGUI and/or Shogidokoro), and then send the "isready" command(type "isready" and Enter key) to see what kind of error you get.

**Comment by rasc42** [comment]
At first, this is what appears:
![image](https://github.com/yaneurao/YaneuraOu/assets/5458405/7a525ba5-02c5-4ca0-b15f-0286ecc85610)

After many newlines:
![image](https://github.com/yaneurao/YaneuraOu/assets/5458405/9ca8027a-905a-4c6c-802e-cf96a3612289)

**Comment by yaneurao** [comment]
Where did you get that model.onnx from?

Can you try it with the model file that can be downloaded from : 

model-dr2_exhi.zip : 
https://github.com/TadaoYamaoka/DeepLearningShogi/releases/tag/dr2_exhi

rename model-dr2_exhi.onnx to model.onnx , and use it.

**Comment by rasc42** [comment]
I got it from the same link!
![image](https://github.com/yaneurao/YaneuraOu/assets/5458405/b161736a-91c0-4636-9e4e-dcac9d25965e)

It's the same files
