### ISSUE TITLE
`setoption name UCT_NodeLimit value 20000000` で変えられない

### ISSUE THREAD

**Issue by Paalon** [yaneurao/YaneuraOu#263]
ふかうらおうで `setoption name UCT_NodeLimit value 20000000` としてノード数上限を変えようと思ったのですが変えられません。

`engine_options.txt` に `option name UCT_NodeLimit type spin default 20000000 min 100000 max 1000000000` とした設定は反映されます。

**Comment by yaneurao** [comment]
テストしてみましたが、変わっているように見えます。

> setoption name UCT_NodeLimit value 20000000
> getoption

```
(略)
Options[ThreadIdOffset] == 0
Options[UCT_NodeLimit] == 20000000
Options[UCT_Threads1] == 2
(略)
```

あと、念のために
> isready
> go infinite
として、
> dlshogi_searcher.cpp(624):
> 		if ( (NodeCountType)(s.current_root->move_count + 1) > o.uct_node_limit)
ここでブレークさせてみたのですが、o.uct_node_limit = 20000000 になっていました。

isready後にsetoptionを実行しているということはないでしょうか？

逆に下限がちょっと高かったので下限は100000→10に変更しておきました。
