### ISSUE TITLE
Resign_thresholdが効いていない？

### ISSUE THREAD

**Issue by tayayan** [yaneurao/YaneuraOu#267]
ふかうら王の探索部ですが、Resign_thresholdをいくつに設定しても、詰みまで投了しないことになっている気がします。

**Comment by yaneurao** [comment]
そういや、Qhapaqさんもそんなこと以前言ってて、私は使わないので未調査のままになってました…。(そもそも未実装の可能性が…)　あとで調べてみますね。

**Comment by yaneurao** [comment]
修正しました。
https://github.com/yaneurao/YaneuraOu/commit/0a6d536db262d8e7efffffb8226e2261714c87ca
