### ISSUE TITLE
王手のかかっている局面をPosition::set_from_packed_sfen()で読むと状態が不正になる

### ISSUE THREAD

**Issue by nodchip** [yaneurao/YaneuraOu#27]
いつもお世話になっております。
王手のかかっている局面をPosition::set_from_packed_sfen()で読むと、Position::pos_is_ok()がfalseを返します。内部でst->checkersBBが0となっているためのようです。
Position::set_from_packed_sfen()内で、	set_state(st) 後に pdate_bitboards() していますが、pdate_bitboards() 後に set_state(st) を呼ぶのが正しいのでしょうか…？

https://github.com/yaneurao/YaneuraOu/blob/a36fbd9128fb140d91e6a3f40bb04db9e1fbfe61/source/extra/sfen_packer.cpp#L438

お手すきの際に確認・修正いただければ幸いです。よろしくお願いいたします。

**Comment by yaneurao** [comment]
ありがとうございます。(｀･ω･´)ゞ
修正しました。

**Comment by nodchip** [comment]
素早い対応ありがとうございました。
