### ISSUE TITLE
MSYS2+clang18で実行できない

### ISSUE THREAD

**Issue by KazApps** [yaneurao/YaneuraOu#278]
MSYS2上でclangのversionを18に上げたところ、ビルド自体はできるのですが実行できなくなりました(clang version 17の時は問題なかった)。
exit codeは-1073741819です。[-1073741819はファイルシステムのエラーのようです。](https://answers.microsoft.com/ja-jp/windows/forum/all/%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%B7/9aae9497-beb8-4658-86df-3ec79f00129b)
動かないのはおそらくYANEURAOU_ENGINE_NNUE系だけだと思います(FukauraOuは試していないからわからない)。
ビルド時にstdlibをlibc++に指定すると実行可能なのでlibstdc++に問題があるということなのでしょうか。

**Comment by yaneurao** [comment]
ご報告ありがとうございます。

⇓この問題だったようで対応しました。
https://github.com/yaneurao/YaneuraOu/commit/db3565eb9b5af30b6162bcefd7818248f073a9dd
