### ISSUE TITLE
将棋所にエンジン登録する時にUSIエンジンではありませんエラーが発生する

### ISSUE THREAD

**Issue by WindVoiceVox** [yaneurao/YaneuraOu#4]
将棋AIを知るきっかけにしようと思いYaneuraOuをgitからcloneしてVisual Studio 2015 Community Editionで使っています。問題といいますか、同じことで悩んでいる方もきっといるのではないかと想像しますのでコメントを書かせて頂きます。

YaneuraOu nano KPP 2.86 64 SSE4.2で使っていますが、将棋所にエンジン登録するときに「USIエンジンではありません」とのエラーが発生します。

原因を調べていたのですが、YaneuraOu.exeを実行すると、直後にbook/standard_book.dbを読み込むための処理が発生します。これに私の環境では、40秒くらいかかっています。この処理は将棋所へのエンジン登録のタイミングでも発生しているため、usiokを返すのが遅れ「USIエンジンでは無い」と診断されてしまうようです。

対局開始時にも同じ処理が発生し40秒ほど待たされますが、しかしこちらはエラーにはならず、動作しています（Bonanza6.0と連続対局中。負けているようです……）

ユーザ側として可能な回避策としては、エンジン登録時にはbook/standard_book.dbを別の名前に変えておくこと（これで短時間でusiokが返るようになる）、エンジン登録が済んだら、もとのファイル名に戻すことが考えられます。

**Comment by yaneurao** [comment]
ああ、
  Book::read_book("book/standard_book.db", book);
は、定跡ファイルが大きいか、HDDが遅い場合、起動時に呼び出されるSearch::Init() ではなく、
isreadyコマンドに対して呼び出されるSearch::clear()のほうで行なうべきですね。修正しておきました。(実行ファイルのほうは、そのうちまとめてコンパイルしなおします。)
