### ISSUE TITLE
learn shuffleコマンドで偏りが出る

### ISSUE THREAD

**Issue by nodchip** [yaneurao/YaneuraOu#45]
learn shuffleコマンドで、シャッフルする局面数が10Mの倍数でない場合にシャッフル結果に偏りが出るようです。例えば10M+1局面シャッフルした場合、10M局面のふぁいると1局面のファイルが生成されます。これらのファイルからランダムにファイルを選択し、局面を書き出していった場合、1局面しか無いファイルの局面がかなりの確率でファイルの先頭に来てしまいます。お手すきの際に確認をお願いできませんでしょうか？よろしくお願いいたします。

本バグはynasu87さんより教えて頂きました。

**Comment by yaneurao** [comment]
まあ、そうですね。手抜き実装なのでそのへんは良いかなぁと思ってます。ここを厳密にしても効果が得られない＆どうせ、1回に生成する局面数は5千万とか1億局面とか、10Mの倍数にすると思うので。とりま、注意書きをどこかに追記しときます。

**Comment by yaneurao** [comment]
注記追加しときました(｀･ω･´)ｂ
https://github.com/yaneurao/YaneuraOu/commit/b1ac69e82a6fc9775e012894082301cc9a2de00c

**Comment by nodchip** [comment]
対応ありがとうございました。

**Comment by yaneurao** [comment]
(｀･ω･´)ゞ

**Comment by yaneurao** [comment]
やっぱり気分悪かったので完全シャッフルするようにしてみました。(｀･ω･´)ｂ
https://github.com/yaneurao/YaneuraOu/commit/b599756c4facdb4f801eb459b96a799794bd40ae
