### ISSUE TITLE
releasesからDLした日本語化ファイル

### ISSUE THREAD

**Issue by Actionintint** [yaneurao/YaneuraOu#53]
ConsiderationMode他いくつかの項が抜けているようですが･･･
多分ミスだと思いますが、仕様だったりしますか

**Comment by yaneurao** [comment]
ファイルが巻き戻ってますね(´ω｀)
gitコマンド、難しい…。

次回、こっちに差し替えておきます。
https://github.com/yaneurao/YaneuraOu/blob/07f4edae0fc7b7f2e4f72a9edc3df7d2dca985fa/exe/2017Early/YaneuraOu-2017-early_ja.txt
