### ISSUE TITLE
通常版使用時に評価関数識別用チェックサムが異なる場合がある

### ISSUE THREAD

**Issue by SurfLapras** [yaneurao/YaneuraOu#60]
通常版（非tournament版）で、評価関数識別用チェックサムがevaluate.cpp内の値と異なる場合があります。
tournament版では発生しません。

SSE4.2版でbenchコマンドを実行して確認しました。

左側はevaluate.cppの値（tournament版での値）、右側が通常版での値

* ShinYane(20161010)
`7171a5469027ebf`→`7171a4e69027eb3`
* Ukamuse(sdt4)
同じ（`71fc7fd40c668cc`）
* elmo
同じ（`65cd7c55a9d4cd9`）
* Yomita(WCSC27)
`3aa68b055a020a8`→`3aa687c55a02303`
* Qhapaq(WCSC27)
同じ（`702fb2ee5672156`）
* tanuki(WCSC27) 
`6c54a1bcb5a6338`→`6c549f3cb5a63b2`

evaluate.cppにはありませんが、以下の評価関数でも確認しました。
* リゼロepoch8  
`58e206e66c06a58`→`58e204466c068b2`
* 野生の読み太(20170703)
`5445b1088b16588`→`5445add88b17343`

また、tanuki(WCSC27)ですがtournament版でもチェックサムが異なるようです。
[tanuki-(WCSC27)のcheck_sumの値を修正](https://github.com/yaneurao/YaneuraOu/commit/4ef434c5525f049e9c57ea8da769a4750e296fce)による修正前と同じ`6c54a1bcb654e37`になっています。

---
実行環境
* OS
Windows Server 2012 R2
* メモリ
32GB
* 使用コンパイラ
MSYS2(clang)

**Comment by yaneurao** [comment]
うおー。端数の初期化されてないメモリまで足してる関係かも知れませんね。あとでコード見直します。
ご指摘、ありがとうございます。

**Comment by yaneurao** [comment]
あー、思い出しました。LEARNが有効だと、KKの先後対称にして元と等しい関係(先手玉28、後手玉22)のところに0を書き込んで補正してるんですけど、これゆえ元の評価関数がそうなってない場合は、check sumの値が変わるんですよね…。この処理、learnコマンド実行時にやるように変更します。(｀･ω･´)ｂ

**Comment by yaneurao** [comment]
修正しときました(｀･ω･´)ゞ
https://github.com/yaneurao/YaneuraOu/commit/5c8a0397f54e61c844f7cc0b4b4221d14871bc73

**Comment by SurfLapras** [comment]
迅速な対応ありがとうございました。

**Comment by yaneurao** [comment]
(｀･ω･´)ゞ

**Comment by Tama4649** [comment]
チェックサムの計算が変わったせいだと思いますが、usi.cppのis_readyて"Error! : evaluate memory is
corrupted"が出ます。
メッセージが出るだけで、その後の処理は動作しているようですが、気持ち悪いので報告まで。


2017年9月10日(日) 6:14 yaneurao <notifications@github.com>:

**Comment by Tama4649** [comment]
すみません。補足です。
KPP_KKPTを有効にして、EVAL_LEARNも有効にして、learnコマンドを実行した時に出ます。
learnで学習した後の評価関数では出なくなります。


2017年9月10日(日) 20:42 たま <tama4649@gmail.com>:

**Comment by yaneurao** [comment]
KPPの1つ目のPと２つ目のPが一致するとき、これはKPであり、KPPに含まれると考えられるので、このKPPの値は0であるべきなのですが、ゼロになっていない評価関数のために、ここをゼロにする処理を入れています。(その他にも同様の考えにもとづいていくつか、ゼロにする処理があります) 以前は、load()の完了同時にやっていたのですが、これだとcheck sumの値が元の評価関数の値とは異なってしまうので、これを、learnコマンドが実行されたときにやるようにしたのですが、それゆえ、learnコマンド直後にcheck sumが変化してしまうので、ここで警告が出ることがあります。まあ、これは、そういうものだということで…。
