### ISSUE TITLE
学習時にメモリ破壊エラーが表示される

### ISSUE THREAD

**Issue by SurfLapras** [yaneurao/YaneuraOu#62]
学習時、「Error! : evaluate memory is corrupted」と表示されます。
5c8a0397f54e61c844f7cc0b4b4221d14871bc73 からのコミットで発生します。

また、benchやgensfenでは起こりません。

---
実行環境
* OS
CentOS 7.3
* メモリ
64GB
* 使用コンパイラ
gcc 6.2.1

**Comment by SurfLapras** [comment]
すでに #60 でも@Tama4649 さんが報告されているみたいですね。
気づかずにissueを建ててしまいました…すみません。

**Comment by yaneurao** [comment]
(｀･ω･´)ゞ　まあ、これはとりあえず仕様ということで…。

**Comment by SurfLapras** [comment]
承知いたしました。ありがとうございました。

**Comment by yaneurao** [comment]
(｀･ω･´)ゞ

**Comment by yaneurao** [comment]
簡単に修正できそうだったので、修正しました。(｀･ω･´)ｂ
https://github.com/yaneurao/YaneuraOu/commit/95a8d0bcce044d5f258f22a16a4188bb323ce8a3

**Comment by Tama4649** [comment]
おぉ！早速の対応、ありがとうこざいます！

2017年9月11日(月) 10:36 yaneurao <notifications@github.com>:

**Comment by SurfLapras** [comment]
対応ありがとうございます。

**Comment by yaneurao** [comment]
(｀･ω･´)ｂ
