### ISSUE TITLE
position.cpp の PieceNumber piece_no =...

### ISSUE THREAD

**Issue by ishidakei** [yaneurao/YaneuraOu#64]
こんにちは。

position.cpp の １９９行目付近について、
すいません、コードの意味合いを理解できてないのですが、 

			PieceNumber piece_no =
				(idx == B_KING) ? PIECE_NUMBER_BKING : // 先手玉
				(idx == W_KING) ? PIECE_NUMBER_WKING : // 後手玉
				piece_no_count[raw_type_of(Piece(idx))]++; // それ以外
				PIECE_NUMBER_ZERO; // とりあえず駒番号は使わないので全部ゼロにしておけばいい。

って、ひょっとして、
piece_no_count から始まる行と PIECE_NUMBER_ZERO から始まる行のどっちかが不要では？ 
あるいは、piece_no_count から始まる行の最後が `;` じゃなくて、`,` っすかね？

**Comment by yaneurao** [comment]
ありがとうございます。コピペしたときのゴミが紛れ込んでいたようです。(´；ω；｀)
extra/sfen_packer.cppのほうは同様の処理で、当該行はないので…。

修正しました！
https://github.com/yaneurao/YaneuraOu/commit/b32b0a660291dca51f44a09a2c4b3e2f889b556a

**Comment by ishidakei** [comment]
:thumbsup:
