### ISSUE TITLE
ponderおよびbookの両方にヒットした時の挙動

### ISSUE THREAD

**Issue by nodchip** [yaneurao/YaneuraOu#66]
一点要望を挙げさせていただきます。
現在のやねうら王の実装では、ponderおよびbookの両方にヒットした場合、bookに登録されている指し手が指されます。これを、
1. bookの指し手を優先する
2. 探索深さが深いほうを優先する
の2通りから選べるようにできませんでしょうか？

2.については、bookに深さ24で探索した指し手が登録されており、ponderが深さ27まで進んでいる場合は、後者を採用するといった感じです。ご一考いただければ幸いです。

**Comment by yaneurao** [comment]
ああ、bookのdepthが信頼できるのであれば、そうなっているのが望ましいですね…。しかしponderhitした場合、現在進行形で探索中なので、そこからbook絡みの処理をするには、usi.cppのほうに手を入れないといけなくて、usi.cppがbookと絡んでくるのは設計として筋が悪いですね…。

このへん、USIプロトコルの設計が良くない意味もあるかと思うのですが、まあとりあえず、この改造は、綺麗に書くのはわりと難しそうなのでSDT5終わってからということにさせてください。(bookのdepthのほうが探索depthより下回る場合、usi.cppでponderhitしていない扱いにするのが良いかとは思います。)

**Comment by yaneurao** [comment]
go ponderされたときにbook hitしていても、そのまま探索は継続してやっておき、ponderhitしたときに、探索深さが深ければそちらを採用するようなオプションがあればいいのだと思うのですが…これを実装するとソースコードがくちゃくちゃになりそうです。本来定跡の指し手自体もGUI側の仕事かなーと思うので、このへん本来ならばGUI側が対処して欲しい意味はありますね…。

GUIのほう、このあと作る予定があるので、そちらで対処しようかなと思ってます。そんなわけで、本件はいったん見送りということにさせてください。(´ω｀)ｽﾐﾏｾﾝ

**Comment by nodchip** [comment]
承知いたしました。対応ありがとうございました。
