### ISSUE TITLE
evaluateBody()内でのでnullポインタアクセス

### ISSUE THREAD

**Issue by nodchip** [yaneurao/YaneuraOu#7]
Learner::search()を呼び出すと、低い確率でevaluateBody()内でnullポインタアクセスによりクラッシュします。

https://github.com/yaneurao/YaneuraOu/blob/e9eee05d265f9d8a74bb1de3254838d8cd97f029/source/eval/evaluate_kppt.cpp#L437
上記の行でprevがnullptrとなる場合があるようです。

調査をお願いいできませんでしょうか？
よろしくお願いいたします。

**Comment by yaneurao** [comment]
StateInfoのprevious == nullとなるのは1) root node 2) null move後のnode
においてのみで、前者のときはPosition::set()で初期化する約束になっていて、
Position::set()のなかではcompute_eval()を呼び出しているので、
evaluate_body()は呼び出されないです。後者のときは、StateInfoのEvalSum sum;
から差分計算できるので、このときもevaluate_body()は呼び出されないので問題ないです。

なので、たぶん、ここで落ちるとしたらroot nodeをPosition::set()以外の方法で
初期化しているのではないかと思うのです。

もしなんでしたらその部分のコード見せてもらえたら調べてみます。

**Comment by yaneurao** [comment]
とりあえずgensfenコマンド実装しました。そちらのほうでは落ちないようなのでこの問題はいったんcloseということで。
