### ISSUE TITLE
SSE無しのときのBitboard ">>="演算

### ISSUE THREAD

**Issue by ai5** [yaneurao/YaneuraOu#8]
SSE無しの時に領域外アクセスで異常終了していたので調べてみると、
Bitboardのシフト演算が逆になっているようです。

Pullリクエストは使い方がよくわからないのでIssueで失礼します。

diff --git a/source/bitboard.h b/source/bitboard.h
index 6429786..648a238 100644
--- a/source/bitboard.h
+++ b/source/bitboard.h
@@ -121,7 +121,7 @@ struct alignas(16) Bitboard
   Bitboard& operator -= (const Bitboard& b1) { this->p[0] -= b1.p[0]; this->p[1] -= b1.p[1]; return *this; }
 
   Bitboard& operator <<= (int shift) { ASSERT_LV3(shift == 1); this->p[0] <<= shift; this->p[1] <<= shift; return *this; }
-  Bitboard& operator >>= (int shift) { ASSERT_LV3(shift == 1); this->p[0] <<= shift; this->p[1] <<= shift; return *this; }
+  Bitboard& operator >>= (int shift) { ASSERT_LV3(shift == 1); this->p[0] >>= shift; this->p[1] >>= shift; return *this; }
 #endif

**Comment by yaneurao** [comment]
あいやー！そんなバグが…。no sse、あまりテストしてなかったので…。benchでnode数が一致するかぐらい調べるべきでしたか…。

いま電王トーナメントに向けて実験したりしている内容、公開したくないんですけど、そこを分けてcommitするのVSのGitHubのプラグインからでは非常に面倒なのでまとめてcommitしておきます。情報だだ漏れ…とほほほほ…。

いずれにせよ、報告ありがとうございます。(｀･ω･´)ゞ
