### ISSUE TITLE
トライルール有効時にトライをしない

### ISSUE THREAD

**Issue by waingo1** [yaneurao/YaneuraOu#99]
入玉ルールでトライルールを選択している場合、一手でトライが可能な局面になってもやねうら王はトライをしません。
また、対戦相手がトライをしても対局終了になりません。
検討モードでもトライの指し手だけ表示されません。

**Comment by yaneurao** [comment]
バグレポありがとうございます。修正しておきました。https://github.com/yaneurao/YaneuraOu/commit/c082e8dc075c5bf425c3b42e6c1c8c5625fc31fa

> また、対戦相手がトライをしても対局終了になりません。

これを判定するのはGUI側ですので…トライルール対応のGUIが必要になります。(『将棋神やねうら王』は対応していますけども、その他のGUIは対応していないはずで…)
